version: "3.4"
services: 
  app-debug: 
      image: bamboo_env
      build: 
        context: ./
        dockerfile: Dockerfile
      volumes: 
         - /Users/taojun/workstation/workspace:/home/jtao/workstation/src/
      #  - /media/xps/jtao_innerspace:/mnt/jtao_innerspace
      networks: 
        - default
      tty: true
networks: 
  default:
    driver: bridge
